#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done 
sleep 4
iw reg set CN 

[ -f /etc/resized ] && resize2fs /dev/mmcblk1p4 && echo done > /etc/resized

export XDG_RUNTIME_DIR=/tmp/weston
weston --tty=7 --idle-time=0 --log=/dev/null &
